### PR TITLE
Authors of the articles

### LINKED ISSUE #36: Last update and author of article is incorrect
## Problems
When navigating pages, we will see all the same last update date and author of the article, which is incorrect.

image

## Expected Results
I suggest that the last update date/time should be the time of the last commit on that page. 
This will help readers to know how up-to-date the information 
for example 2 minutes ago and 2 years ago are very different.

The author's name should be all of the contributors of that page as we can see from the Microsoft Docs site.

image

### PR DESCRIPTION
**Pull request by mildronize**
image

please review my PR. ;)

### CODE REVIEW

File: src/components/Authors/Authors.tsx [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+export interface IAuthorInfo{
+  username?: string; 
+  name: string;
+  commits: number;
+  url: string;
+}
+
+const initAuthorList :IAuthorInfo[] = [];
+
+const Authors = styled(({ className, path,  repoType, repo, contentRootPath, locationPathname}: IAuthorsProps) => {
```
Comment (aaronamm) [inline src/components/Authors/Authors.tsx:30]: Such a good TypeScript Code, you define an interface for a parameter.

File: src/components/Authors/Authors.tsx [hunk 2]
```diff
@@ -0,0 +1,108 @@
...
+
+  const fetchContributors = async () => {
+
+    const axiosConfig = {
+      headers: {
+        'Accept': 'application/vnd.github.v3+json'
+      }
+    }
+    const response = await axios.get(contributorsGithubAPI,axiosConfig);
+    console.log(response.data);
```
Comment (aaronamm) [inline src/components/Authors/Authors.tsx]: Please remove console.log. ^^

File: src/components/Authors/Authors.tsx [hunk 3]
```diff
@@ -0,0 +1,108 @@
...
+
+    const authors: Record<string, IAuthorInfo> = {};
+    response.data.map( commit => {
+      // Get Github username or Email.
+      const author = commit?.author?.login || commit?.commit?.author.email;
+      if(!author) return;
+      console.log(commit);
```
Comment (aaronamm) [inline src/components/Authors/Authors.tsx]: Please remove console.log. ^^

File: src/components/Authors/Authors.tsx [hunk 4]
```diff
@@ -0,0 +1,108 @@
...
+    });
+
+    const authorListTmp:IAuthorInfo[] = [];
+    for (const [key, value] of Object.entries(authors)) {
+      authorListTmp.push({
+        ...value,
+        username: key
+      });
+    }
+    authorListTmp.sort((a, b) => (a.commits < b.commits) ? 1 : -1);
```
Comment (aaronamm) [inline src/components/Authors/Authors.tsx]: 👍

File: src/components/Authors/Authors.tsx [hunk 5]
```diff
@@ -0,0 +1,108 @@
...
+import { format } from 'date-fns';
+import styled from '@emotion/styled';
+import axios from 'axios';
+
+/*
+Require: config.features.editOnRepo.editable = true
+We collect `Author` field, ref: https://stackoverflow.com/a/6755848/4540808
+*/
+
+export interface IAuthorsProps{
```
Comment (aaronamm) [inline src/components/Authors/Authors.tsx]: It looks like we use IAuthorsProps only inside this module, so you don't need to export it.
Please remove `export`.

File: src/components/Authors/Authors.tsx [hunk 6]
```diff
@@ -0,0 +1,108 @@
...
+  display: block;
+
+  a, a:active, a:visited { 
+    color: ${(props) => props.theme.colors.primary}
+  }
+
+  a:hover {
+    color: ${(props) => props.theme.colors.primaryDark}
+  }
+`;
```
Comment (aaronamm) [inline src/components/Authors/Authors.tsx:111]:
```tsx
})`
  font-size: 12px;
  display: block;
  a, a:active, a:visited { 
    color: ${(props) => props.theme.colors.primary}
  }
  a:hover {
    color: ${(props) => props.theme.colors.primaryDark}
  }
`;

````
Does this code fragment work, or valid if not, please remove it.
You can use style component/CSS prop if you need to style a component.
We've already used Emotion in our project.

File: src/components/Authors/index.ts [hunk 7]
```diff
@@ -0,0 +1 @@
+export { default } from './Authors';
```
Comment (aaronamm) [inline src/components/Authors/index.ts:1]: I am not sure this is a good practice of how to structure your JS project.
However, if my component has only one file, I won't create it parent folder but I think later if we have other resources or unit test, this is reasonable.

File: src/templates/docs.js [hunk 8]
```diff
@@ -146,15 +130,14 @@ export default class MDXRuntimeTest extends React.Component {
...
-                ''
-              )}
+              {mdx.parent.relativePath && docsRepo && docsLocationType && contentRootPath &&
+                <Authors 
+                  path={mdx.parent.relativePath}
+                  repo={docsRepo}
+                  repoType={docsLocationType}
+                  contentRootPath={contentRootPath}
+                  locationPathname={this.props.location.pathname}
+                  />}
```
Comment (aaronamm) [inline src/templates/docs.js:140]: So this brock will be return empty as a default so we don't need to set `''` right?

**Comment by kaiwanyawit-chawankul** [comment]
Looks good for me 

Screen Shot 2564-08-05 at 22 21 41

Source
Screen Shot 2564-08-05 at 22 21 34

I thought this fix for issue https://github.com/dotnetthailand/dotnetthailand.github.io/issues/36

What do you think cc @aaronamm

**Comment by kaiwanyawit-chawankul** [comment]
@mildronize Could you please help me remove this trailing comma?
Screen Shot 2564-08-05 at 22 25 48

File: src/components/Authors/Authors.tsx [hunk 9]
```diff
@@ -0,0 +1,108 @@
...
+
+  useEffect(()=> {
+    setAuthorList([]);
+    fetchContributors();
+  }, [locationPathname]);
+  
+  return (
+    <span className={className}>
+     Last update: {lastUpdate}<br/>
+     Authors: {authorList.map(author => (
```
Comment (kaiwanyawit-chawankul) [inline src/components/Authors/Authors.tsx:90]: trailing comma

File: src/components/Authors/Authors.tsx [hunk 10]
```diff
@@ -0,0 +1,108 @@
...
+       <span key={author.username}><a href={author.url} target="_blank" rel="noreferrer">{author.name}</a>, </span>
+     ))}
```
Comment (kaiwanyawit-chawankul) [inline src/components/Authors/Authors.tsx]: this code will produce trailing comma when we have only one author

**Comment by mildronize** [comment]
@kaiwanyawit-chawankul Thank you for testing the UI, I'll fix that last comma latter. 

Thank you for your contribution. Your effort is meaningful. :)

File: src/components/Authors/Authors.tsx (hunk 10 above)
Comment (mildronize) [reply src/components/Authors/Authors.tsx]: Yes, thank you so much.

Comment (mildronize) [reply src/components/Authors/Authors.tsx]: I've done, I'll commit later

```jsx
{names.map((name, index) => (
  <>
    {name}
    {names.length - 1 === index? '' : ','}
  </>
))}
```

Comment (mildronize) [reply src/components/Authors/Authors.tsx]: Done

**Review by kaiwanyawit-chawankul — APPROVED** [review]
It looks good for me

**Comment by kaiwanyawit-chawankul** [comment]
@aaronamm Please check this PR

File: src/components/Authors/Authors.tsx [hunk 11]
```diff
@@ -0,0 +1,106 @@
...
+  repo: string;
+  contentRootPath: string;
+  locationPathname: string;
+}
+
+export interface IAuthorInfo{
+  username?: string; 
+  name: string;
+  commits: number;
+  url: string;
```
Comment (aaronamm) [inline src/components/Authors/Authors.tsx]: I suggest to update some properties to more specific meaning,e.g.

```ts

interface IAuthorInfo {
  username?: string;
  commitsCount: number;
  profileUrl: string;
}
```


I think we can remove name and use username for displaying and react list key because it is unique value.

File: src/components/Authors/Authors.tsx [hunk 12]
```diff
@@ -0,0 +1,106 @@
...
+
+    const authorListTmp:IAuthorInfo[] = [];
+    for (const [key, value] of Object.entries(authors)) {
+      authorListTmp.push({
+        ...value,
+        username: key
+      });
+    }
+    authorListTmp.sort((a, b) => (a.commits < b.commits) ? 1 : -1);
+    setAuthorList([...authorListTmp]);
```
Comment (aaronamm) [inline src/components/Authors/Authors.tsx]: For this block of code that we want to get a unique and sorted by commits count author, I suggest to use more declarative code, less mutate an object.

```ts

    // Map all commit to duplicated authors.
    const allAuthors: IAuthorInfo[] = response.data.map(commit => {
      return {
        // Get Github username or Email, sometime we can't get author from the API.
        username: commit?.author?.login || commit?.commit?.author.email,
        profileUrl: commit?.author?.html_url || commit?.html_url,
        commitsCount: 1, // default to 1
      };
    });

    // Create a unique author and increase commits count if an author has more than one commit.
    const uniqueAuthors = allAuthors.reduce((authors, currentAuthor) => {
      const usernameKey = currentAuthor.username;
      const uniqueAuthor = authors[usernameKey];
      if (uniqueAuthor) {
        uniqueAuthor.commitsCount++;
      } else {
        authors[usernameKey] = currentAuthor;
      }

      return authors;
    }, {} as Record<string, IAuthorInfo>);

    // Flatting to array of author and sort by commits number descending
    const sortedByCommitsCountAuthors = Object.entries(uniqueAuthors)
      .map(([, author]) => author)
      .sort((a, b) => (a.commitsCount < b.commitsCount) ? 1 : -1)

    // Set to React state
    setAuthorList([...sortedByCommitsCountAuthors]);
```

**Review by aaronamm — CHANGES_REQUESTED** [review]
Very good PR, just a little PR feedback.

**Comment by aaronamm** [comment]
@mildronize  very minor issue, we don't need , for a single author.
image

File: src/components/Authors/Authors.tsx [hunk 13]
```diff
@@ -87,8 +87,10 @@ const Authors = styled(({ className, path,  repoType, repo, contentRootPath, loc
   return (
     <span className={className}>
      Last update: {lastUpdate}<br/>
-     Authors: {authorList.map(author => (
-       <span key={author.username}><a href={author.url} target="_blank" rel="noreferrer">{author.name}</a>, </span>
+     Authors: {authorList.map((author, authorIndex) => (
+       <span key={author.username}><a href={author.url} target="_blank" rel="noreferrer">{author.name}</a>
+       {authorList.length -1 === authorIndex? '' : ', '}
+       </span>
```
Comment (aaronamm) [inline src/components/Authors/Authors.tsx:95]: 👍

File: src/components/Authors/Authors.tsx [hunk 14]
```diff
@@ -75,10 +75,6 @@ const Authors = styled(({ className, path,  repoType, repo, contentRootPath, loc
     setLastUpdate(format(new Date(lastCommitDate),"MMM dd, yyyy"));
   }
 
-  useEffect(()=> {
```
Comment (aaronamm) [inline src/components/Authors/Authors.tsx]: 👍 👍 👍 👍 👍

File: src/components/Authors/Authors.tsx (hunk 2 above)
Comment (mildronize) [reply src/components/Authors/Authors.tsx]: Oh, my fault, thank you.

File: src/components/Authors/Authors.tsx (hunk 3 above)
Comment (mildronize) [reply src/components/Authors/Authors.tsx]: Yes, thank you

File: src/components/Authors/index.ts (hunk 7 above)
Comment (mildronize) [reply src/components/Authors/index.ts:1]: I use the same pattern of the rest of other components.

File: src/components/Authors/Authors.tsx (hunk 6 above)
Comment (mildronize) [reply src/components/Authors/Authors.tsx:111]: Yes, it works properly.  I've used `@emotion/styled` as you can see in https://github.com/dotnetthailand/dotnetthailand.github.io/pull/109/files/1e7cb7638837254b1e893580ee01a1bafd453e9c#diff-d6834de941206efe92b304b516bebc6f2237a772876888fcca9ce730c112704eR30

File: src/templates/docs.js (hunk 8 above)
Comment (mildronize) [reply src/templates/docs.js:140]: Yes.

File: src/components/Authors/Authors.tsx (hunk 11 above)
Comment (mildronize) [reply src/components/Authors/Authors.tsx]: I want to show the `name` prop instead of `username` prop.

File: src/components/Authors/Authors.tsx (hunk 12 above)
Comment (mildronize) [reply src/components/Authors/Authors.tsx]: I'll investigate on that.

File: src/components/Authors/Authors.tsx (hunk 5 above)
Comment (mildronize) [reply src/components/Authors/Authors.tsx]: Oh, I see thank you.

File: src/components/Authors/Authors.tsx (hunk 11 above)
Comment (aaronamm) [reply src/components/Authors/Authors.tsx]: @mildronize  but we can keep only one property right?

File: src/components/Authors/Authors.tsx (hunk 2 above)
Comment (aaronamm) [reply src/components/Authors/Authors.tsx]: @mildronize  No worries, we should have some automated process to detect console.log.

File: src/components/Authors/Authors.tsx (hunk 12 above)
Comment (mildronize) [reply src/components/Authors/Authors.tsx]: Nice suggestion, thank you so much.!

File: src/components/Authors/Authors.tsx [hunk 15]
```diff
@@ -41,34 +41,40 @@ const Authors = styled(({ className, path,  repoType, repo, contentRootPath, loc
...
-      });
-    }
-    authorListTmp.sort((a, b) => (a.commits < b.commits) ? 1 : -1);
-    setAuthorList([...authorListTmp]);
+          profileUrl: commit?.author?.html_url || commit?.html_url,
+          commitsCount: 1, // default to 1
+        };
+      })
+      // Remove author if username is undefined 
+      .filter(currentAuthor => currentAuthor.username);
```
Comment (aaronamm) [inline src/components/Authors/Authors.tsx:56]: 👍

File: src/components/Authors/Authors.tsx [hunk 16]
```diff
@@ -84,7 +90,7 @@ const Authors = styled(({ className, path,  repoType, repo, contentRootPath, loc
     <span className={className}>
      Last update: {lastUpdate}<br/>
      Authors: {authorList.map((author, authorIndex) => (
-       <span key={author.username}><a href={author.url} target="_blank" rel="noreferrer">{author.name}</a>
+       <span key={author.username}><a href={author.profileUrl} target="_blank" rel="noreferrer">{author.name}</a>
```
Comment (aaronamm) [inline src/components/Authors/Authors.tsx:93]: 👍

File: src/components/Authors/Authors.tsx [hunk 17]
```diff
@@ -41,34 +41,40 @@ const Authors = styled(({ className, path,  repoType, repo, contentRootPath, loc
...
-      if (author in authors){
-        authors[author].commits ++;
-      } else{
-        authors[author] = {
+    const allAuthors: IAuthorInfo[] = response.data
+      // Map all commit to duplicated authors.
+      .map(commit => {
+        return {
+          // Get Github username or Email, sometime we can't get author from the API.
+          username: commit?.author?.login || commit?.commit?.author.email,
```
Comment (aaronamm) [inline src/components/Authors/Authors.tsx:49]: 👍

**Comment by aaronamm** [comment]
@mildronize Such a nice PR. Thank you so much.

**Review by aaronamm — APPROVED** [review]
