### PR TITLE
fix: issue Sub menu not expanded on clicking link #117

### LINKED ISSUE #117: Sub menu not expanded on clicking link
https://user-images.githubusercontent.com/248741/128623407-ba5bef5d-6316-4485-893e-ebf436278ef7.mov

The submenu is not expanded when clicking on the text eg. `Testing > Jest`, while on the main menu it was expanded normally eg. `Testing`. Now I have to click at the `^` icon to expand the sub-menu.

### PR DESCRIPTION
**Pull request by mildronize**
Please review my PR.

### CODE REVIEW

File: src/components/Sidebar/contentTree.js [hunk 1]
```diff
@@ -137,7 +137,9 @@ const ContentTree = ({ edges, location, menuOpen }) => {
 
   }
 
-  const handleLinkClick = () => {
+  const handleLinkClick = (ev, link) => {
+    // Expand nav on clicking link
+    link.isExpanded = true;
```
Comment (aaronamm) [inline src/components/Sidebar/contentTree.js:142]: 👍 
Thanks.

**Review by aaronamm — APPROVED** [review]
Nice PR, thank you.
